### ISSUE TITLE
Incorrect sender address was returned

### ISSUE THREAD

**Issue by allush** [zksync-sdk/zksync2-go#13]
There is transaction on ZkSync Era https://explorer.zksync.io/tx/0x197058ca77d906d883f75c1a720b414142092b27862f344044411b7268c7169e

Library returns incorrect sender address for this transaction -`0x120982a08B06f31583c10F0383a2C3aa46f06606`

Actual sender address is `0xBB4ddF60b4013B10E7D1709DED7f4B8A81398073`

Code for reproduce

	ctx := context.Background()
	zp, err := zksync2.NewDefaultProvider("https://mainnet.era.zksync.io")
	if err != nil {
		panic(err)
	}

	txHash := "0x197058ca77d906d883f75c1a720b414142092b27862f344044411b7268c7169e"
	tx, _, err := zp.GetClient().TransactionByHash(ctx, common.HexToHash(txHash))
	if err != nil {
		panic(err)
	}

	signer := types.LatestSignerForChainID(new(big.Int).SetUint64(324))
	sender, err := signer.Sender(tx)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s \n", sender)

How to get actual sender address?

**Comment by allush** [comment]
This code works fine:

```
func (tx *Transaction) From() common.Address {
	return tx.from.Load().(sigCache).from
}
```

**Comment by tiennampham23** [comment]
@allush use `l2tx, err := zp.GetTransaction(txHash)` instead `zp.GetClient().TransactionByHash(txHash)`

And you can get
```go
from := l2tx.From
```

**Comment by danijelTxFusion** [comment]
zp.GetClient() returns instance of ethclient.Client which should be used internally because some of the RPC method are not compatible with zkSync node. That's why it will be removed because it introduces a lot of confusions among users.

**Comment by allush** [comment]
ok, thanks @danijelTxFusion @tiennampham23
