### ISSUE TITLE
full context support

### ISSUE THREAD

**Issue by hardstylez72** [zksync-sdk/zksync2-go#17]
Hi guys! Is it possible to make context support for all funcs where it is needed? May I make a pull request for that addon?

**Comment by danijelTxFusion** [comment]
Context support will be included in next release. You can take a look at [this](https://github.com/zksync-sdk/zksync2-go/blob/938f5cc0845b5d5761eab2f8b2facc835f3b2422/clients/client.go#L20) branch.

**Comment by danijelTxFusion** [comment]
Context support is implemented in version `v0.3.0`.
