### ISSUE TITLE
walletL1 BalanceL1 bug

### ISSUE THREAD

**Issue by lojijkl** [zksync-sdk/zksync2-go#22]
`func (a *WalletL1) BalanceL1(opts *CallOpts, token common.Address) (*big.Int, error) {
	callOpts := ensureCallOpts(opts).ToCallOpts(a.auth.From)
	if token == utils.EthAddress {
		return a.clientL1.BalanceAt(opts.Context, a.auth.From, opts.BlockNumber)
	} else {
		erc20Contract, err := erc20.NewIERC20(token, a.clientL1)
		if err != nil {
			return nil, fmt.Errorf("failed to load IERC20: %w", err)
		}
		return erc20Contract.BalanceOf(callOpts, a.auth.From)
	}
}` 
when I call this function have nil address error 
maybe `
return a.clientL1.BalanceAt(opts.Context, a.auth.From, opts.BlockNumber)
`
fix to
`
 return a.clientL1.BalanceAt(callOpts.Context, a.auth.From, callOpts.BlockNumber)
`
?

**Comment by danijelTxFusion** [comment]
Nice catch. I will create new release with fix.
