### ISSUE TITLE
`/tests` Missing

### ISSUE THREAD

**Issue by idea404** [zksync-sdk/zksync2-go#25]
#### 📝 Description

Repository is missing tests to assert functionality. This issue is meant to track this missing implementation which is currently blocked by a bug in https://github.com/matter-labs/local-setup that errors when the functions `zks_getMainContract` and `zks_estimateGasL1toL2` are called.

**Comment by danijelTxFusion** [comment]
Tests are added to main branch and made to work with latest stable version of local-setup. Also [CI](https://github.com/zksync-sdk/zksync2-go/pull/26/checks) is added which runs tests and additional checks on every PR.
