### ISSUE TITLE
go dependency version too old

### ISSUE THREAD

**Issue by yibishufange** [zksync-sdk/zksync2-go#29]
this repo depend on github.com/miguelmota/go-ethereum-hdwallet, which uses github.com/btcsuite/btcutil/hdkeychain, and btcsuite has already move btcutil to [github.com/btcsuite/btcd/btcutil](https://github.com/btcsuite/btcd/tree/master/btcutil) which is under btcd repo, so if i use zksync-go and other repo depend on btcsuite/btcd/btcutil，confilct will happen. 

here is the go mod tidy error output message:
  github.com/zksync-sdk/zksync2-go/accounts imports
        github.com/miguelmota/go-ethereum-hdwallet imports
        github.com/btcsuite/btcutil/hdkeychain imports
        github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.24.0), but does not contain package github.com/btcsuite/btcd/btcec

you can fork this repo and update its go mod dependency or use this instead:https://github.com/stephenlacy/go-ethereum-hdwallet

**Comment by danijelTxFusion** [comment]
Thanks for reporting this issue. I will change dependency to `https://github.com/stephenlacy/go-ethereum-hdwallet` since latest version of `github.com/miguelmota/go-ethereum-hdwallet` still uses the old `btcutil` dependency.

**Comment by danijelTxFusion** [comment]
Fixed in `v0.4.0`.
