### ISSUE TITLE
Provide Paymaster example for contract interaction

### ISSUE THREAD

**Issue by alrevuelta** [zksync-sdk/zksync2-go#52]
### 🌟 Feature Request

Provide an example of how to use the Paymaster so that a user can interact gas-free with a given contract. Let say that there is a `Contract` with a function `functionA(arg1, arg2)` that emits an event `Event1`. I would like to use the Paymaster to interact with `Contract` gas-free to call `functionA(arg1, arg2)` so that `Event1` is emitted. After reading [paymaster](https://docs.zksync.io/build/zksync-101/paymaster) docs and playing around with this repo, can't find a way to do so. Perhaps provide an example similar to [interactWithGaslessPaymaster.ts](https://github.com/matter-labs/zksync-contract-templates/blob/main/templates/quickstart/hardhat/paymaster/deploy/interact/interactWithGaslessPaymaster.ts) which is TypeScript.

#### 📝 Description

Example written using this library to accomplish what is suggested above.

#### 🤔 Rationale

Easier to onboard devs to the Paymater feature.

**Comment by danijelTxFusion** [comment]
Here is the [example](https://docs.zksync.io/sdk/go/guides/features#see-in-action) on how to do interact with contract using paymaster. Also here's the complete [example](https://github.com/zksync-sdk/zksync2-examples/blob/main/go/18_use_paymaster.go) with contracts that are already deployed on Sepolia.

**Comment by alrevuelta** [comment]
Amazing, thanks.
